{
 "title": "Greenplum Real Time",
 "time": { "from": "2018-10-17T03:32:17.208Z", "to": "2018-10-17T04:11:31.258Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "d",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day',now() - pg_postmaster_start_time()) as value"
    }
   ]
  },
  {
   "title": "Segment Instances",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(status) \nFROM gp_segment_configuration \nWHERE status = 'u';"
    }
   ]
  },
  {
   "title": "System History",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  load0\nFROM system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  ctime AS \"time\",\n  cpu_user\nFROM system_history\nWHERE\n  $__timeFilter(ctime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Replication Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n       CASE WHEN sync_state='sync' THEN 1\n            ELSE 2\n       END\n    FROM pg_stat_replication;"
    }
   ]
  },
  {
   "title": "Query Dashboard",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\ndatname as Database,\nprocpid as Process_ID,\nsess_id as Session_ID,\nusename as Username,\nSUBSTR(current_query,0,60) as Current_Query,\nnow() - query_start as Query_Duration,\nnow() - backend_start as Session_Duration,\nwaiting as Is_Waiting\nFROM pg_stat_activity\nWHERE current_query NOT ilike '%IDLE%'\nORDER BY 6 desc;"
    }
   ]
  }
 ]
}